// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYJbt5DZcjEENhs02OTKaLy9Nzy-6qOE',
    appId: '1:988167689804:web:50b7a60caf13c3179e06e9',
    messagingSenderId: '988167689804',
    projectId: 'ordertracking-40f65',
    authDomain: 'ordertracking-40f65.firebaseapp.com',
    storageBucket: 'ordertracking-40f65.firebasestorage.app',
    measurementId: 'G-6LN78YP9SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_5Y7XbznpLDhAnMLSai9neEwjjrl2Wk',
    appId: '1:988167689804:android:230dec1ecf21921e9e06e9',
    messagingSenderId: '988167689804',
    projectId: 'ordertracking-40f65',
    storageBucket: 'ordertracking-40f65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFJ6M_gbKXpKlnz12QNONx214WDjFCeoM',
    appId: '1:988167689804:ios:eb785a7e02aedc3a9e06e9',
    messagingSenderId: '988167689804',
    projectId: 'ordertracking-40f65',
    storageBucket: 'ordertracking-40f65.firebasestorage.app',
    iosBundleId: 'com.example.orderTrackingApp',
  );
}
